// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtULJE9WA-TqVcsNRZymydINaMFVTP5DI',
    appId: '1:544294646910:web:1142754e469fba695e142f',
    messagingSenderId: '544294646910',
    projectId: 'ggc-2024',
    authDomain: 'ggc-2024.firebaseapp.com',
    storageBucket: 'ggc-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD2mRgStlcc7WxtUffEI6v8r9bo8lHrYw',
    appId: '1:544294646910:android:afac191fb5cdea125e142f',
    messagingSenderId: '544294646910',
    projectId: 'ggc-2024',
    storageBucket: 'ggc-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfp_qU0EfClM1a8enclBCxTrNKUVXeSuI',
    appId: '1:544294646910:ios:5e2cd0fd55bf09e45e142f',
    messagingSenderId: '544294646910',
    projectId: 'ggc-2024',
    storageBucket: 'ggc-2024.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfp_qU0EfClM1a8enclBCxTrNKUVXeSuI',
    appId: '1:544294646910:ios:ad792b83f5912fc95e142f',
    messagingSenderId: '544294646910',
    projectId: 'ggc-2024',
    storageBucket: 'ggc-2024.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
